insert into Categories([Name], [Description])
values	 ('Category_1', 'Description_for_category_1')
		,('Category_2', 'Description_for_category_2')
		,('Category_3', 'Description_for_category_3')
		,('Category_4', 'Description_for_category_4')
		,('Category_5', 'Description_for_category_5')
		,('Category_6', 'Description_for_category_6')
		,('Category_7', 'Description_for_category_7')
		,('Category_8', 'Description_for_category_8')
		,('Category_9', 'Description_for_category_9')
		,('Category_10', 'Description_for_category_10')
		,('Category_11', 'Description_for_category_11')