insert into Products ([Name], [Description])
values	 ('Product_1', 'Description_for_product_1')
		,('Product_2', 'Description_for_product_2')
		,('Product_3', 'Description_for_product_3')
		,('Product_4', 'Description_for_product_4')
		,('Product_5', 'Description_for_product_5')
		,('Product_6', 'Description_for_product_6')
		,('Product_7', 'Description_for_product_7')
		,('Product_8', 'Description_for_product_8')
		,('Product_9', 'Description_for_product_9')
		,('Product_10', 'Description_for_product_10')
		,('Product_11', 'Description_for_product_11')